# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-squ',
                'doc_host': 'https://adonm.github.io',
                'git_url': 'https://github.com/adonm/nbdev-squ',
                'lib_path': 'squ'},
  'syms': { 'squ.api': { 'squ.api.atlaskit_transformer': ('api.html#atlaskit_transformer', 'squ/api.py'),
                         'squ.api.list_securityinsights': ('api.html#list_securityinsights', 'squ/api.py'),
                         'squ.api.list_subscriptions': ('api.html#list_subscriptions', 'squ/api.py'),
                         'squ.api.list_workspaces': ('api.html#list_workspaces', 'squ/api.py'),
                         'squ.api.loganalytics_query': ('api.html#loganalytics_query', 'squ/api.py')},
            'squ.clients': {'squ.clients.foo': ('clients.html#foo', 'squ/clients.py')},
            'squ.core': { 'squ.core._cli': ('core.html#_cli', 'squ/core.py'),
                          'squ.core.azcli': ('core.html#azcli', 'squ/core.py'),
                          'squ.core.datalake_path': ('core.html#datalake_path', 'squ/core.py'),
                          'squ.core.load_config': ('core.html#load_config', 'squ/core.py'),
                          'squ.core.login': ('core.html#login', 'squ/core.py')}}}
