# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-squ',
                'doc_host': 'https://adonm.github.io',
                'git_url': 'https://github.com/adonm/nbdev-squ',
                'lib_path': 'nbdev_squ'},
  'syms': {'nbdev_squ.core': {'nbdev_squ.core.foo': ('core.html#foo', 'nbdev_squ/core.py')}}}
